class PDAHandler ui {
	virtual void buttonClickCommand(PDAButton caller, string command) {
	}
	virtual void buttonRClickCommand(PDAButton caller, string command) {
	}
	virtual void buttonHeldCommand(PDAButton caller, string command) {
	}
	virtual void buttonHalfHeldCommand(PDAButton caller, string command) {
	} 
	virtual void elementHoverChanged(PDAElement caller, string command, bool unhovered) {
	}
}